"""Generate ALL_ANSWERS.md: every question, every site, every answer.

    python3 make_all_answers.py

Reads results/run.json and writes ALL_ANSWERS.md: all 75 (question, site) pairs
with Mireye's verbatim answer, the no-data model's value where a head-to-head was
run, any field the oracles marked wrong, and any data_gaps.

Regenerate this after any new run.py. It reads only saved results, so it needs no
API keys and no network.
"""

import collections
import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent))
from earthbench.fixtures.questions import QUESTIONS

RUN = pathlib.Path("results/run.json")
DEST = pathlib.Path("ALL_ANSWERS.md")

EXPECT_MEANS = {
    "answer": "the data supports an answer and it should give one",
    "refuse": "the decisive field does not exist in Mireye; it should say so",
    "hedge": "the data supports an answer but the value is coarse or not the "
             "authority a real decision-maker uses",
    "decline": "the question requires comparing coordinates, and /ask takes one point",
}
OUTCOMES = {
    "mireye_wins": "**Mireye wins**", "model_wins": "**model wins**",
    "both_right": "both right", "both_refuse": "both refused",
    "no_oracle": "no oracle for this one",
}


def fmt(v):
    if v is None:
        return "n/a"
    return f"{v:.2f}" if isinstance(v, float) else str(v)


def main():
    qt = {q.id: q for q in QUESTIONS}
    order = [q.id for q in QUESTIONS]
    recs = json.loads(RUN.read_text())

    byq = collections.OrderedDict((k, []) for k in order)
    for r in recs:
        byq.setdefault(r["question"], []).append(r)

    out = [
        "# Every question, every site, every answer", "",
        f"All {len(recs)} (question, site) pairs from `results/run.json`, verbatim.",
        "`/ask` is non-deterministic; these are the sample-0 responses.", "",
        "Where a head-to-head was run, the no-data model's answer is shown beneath",
        "Mireye's. Only its value and confidence were saved, not its prose.", "",
        "Generated by `make_all_answers.py`.", "",
        "## Contents", "",
    ]
    for k in order:
        q = qt[k]
        out.append(f"- [{q.id}](#{q.id}) · “{q.text}” · expect **{q.expect}** · "
                   f"{len(byq.get(k, []))} sites")
    out.append("")

    for k in order:
        rs = byq.get(k, [])
        if not rs:
            continue
        q = qt[k]
        out += ["\n---\n", f"# {q.id}", "", f"**Question asked:** “{q.text}”", "",
                f"**Correct behavior:** `{q.expect}`, {EXPECT_MEANS.get(q.expect, '')}", ""]
        if q.decisive:
            out.append(f"**Decisive field(s):** `{'`, `'.join(sorted(q.decisive))}`\n")
        if q.note:
            out.append(f"**Why this question:** {q.note}\n")

        for r in sorted(rs, key=lambda x: x["site"]):
            u = r.get("uncertainty") or {}
            mark = "PASS" if u.get("correct_behavior") else "**FAIL**"
            flags = []
            if u.get("false_answer"):
                flags.append("**FALSE ANSWER**")
            if u.get("false_refusal"):
                flags.append("false refusal")
            out += [f"\n### {r['site']} · {mark}",
                    f"*did: {u.get('behavior', '?')} · confidence: {r.get('confidence', '?')} · "
                    f"{r.get('n_citations', 0)} citations"
                    f"{' · ' + ', '.join(flags) if flags else ''}*", "",
                    "**Mireye:**", ""]
            out.append("> " + (r.get("answer") or "").strip().replace("\n", "\n> "))

            h = r.get("head_to_head")
            if h:
                model = ("refused to answer" if h.get("model_refused")
                         else f"`{fmt(h.get('model_value'))}`")
                out += ["",
                        f"**No-data model:** {model} ({h.get('model_confidence', '?')} confidence)  ",
                        f"**Mireye value:** `{fmt(h.get('mireye'))}` · "
                        f"**Truth:** `{fmt(h.get('truth'))}` · "
                        f"**Result:** {OUTCOMES.get(h.get('outcome'), h.get('outcome'))}"]

            wrong = [c for c in (r.get("correctness") or []) if c.get("correct") is False]
            if wrong:
                out.append("")
                for c in wrong:
                    out.append(f"- WRONG `{c['field']}`: got `{c.get('got')}`, "
                               f"truth `{c.get('expected')}`, oracle: {c.get('oracle', '?')}")
            if r.get("data_gaps"):
                out.append(f"\n- `data_gaps`: {json.dumps(r['data_gaps'])[:280]}")
            out.append("")

    DEST.write_text("\n".join(out))
    print(f"wrote {DEST}: {len(recs)} pairs, {DEST.stat().st_size // 1024} KB")


if __name__ == "__main__":
    main()
